#!/bin/bash

# Check if any command-line arguments were passed
if [ $# -gt 0 ]
then
  # The first argument is the custom docker command shell provided by the plugin
  # The second argument is the Java command line generated by the plugin (passed as a single argument)
  shift
  
  # Execute the custom docker command shell, passing the Java command line as an argument
  exec /bin/sh -c "$@"
fi
