#!/bin/bash
if [ $# -gt 0 ]
then
  # first argument is the custom docker command shell provided by plugin
  # second argument is the java command line generated by the plugin (passed as a single arg)
  shift
  exec /bin/sh -c "$@"
fi
